import type { ComponentStyleConfig } from '@chakra-ui/theme'

export const Button: ComponentStyleConfig = {
  baseStyle: {
    _hover: {
      _disabled: { bg: 'auto', filter: 'saturate(0%)' },
    },
    _disabled: { filter: 'saturate(0%)' },
  },
  variants: {
    primary_button: {
      h: 'auto',
      borderRadius: 60,
      color: 'main_white',
      bg: 'blue.500',
      fontWeight: 700,
      _focus: {
        boxShadow: 'none',
      },
    },
    iconBtn: {
      borderRadius: 0,
      h: 'auto',
      w: 'auto',
      minW: 0,
      minH: 0,
      p: 1,
      bg: 'transparent',
    },
    secondary_button: {
      h: 'auto',
      borderRadius: 60,
      border: '1px solid',
      borderColor: 'blue.500',
      color: 'blue.500',
      fontWeight: 700,
      _focus: {
        boxShadow: 'none',
      },
    },
    outlined_button: {
      border: '1px solid',
      borderColor: 'blue.500',
      borderRadius: 60,
      py: 4,
      px: 8,
      mx: 2,
      h: 'auto',
      w: 'fit-content',
      bg: 'none',
      color: 'gray.200',
      cursor: 'pointer',
      _disabled: {
        cursor: 'not-allowed',
      },
    },
    button_ordinary: {
      mx: 2,
      py: 3,
      px: 4,
      fontSize: 14,
      borderRadius: 60,
      color: 'main_white',
      bg: 'blue.500',
      fontWeight: 600,
      _focus: {
        boxShadow: 'none',
      },
    },
    button_large: {
      h: 'auto',
      w: 'fit-content',
      mx: 2,
      py: 4,
      px: 8,
      borderRadius: 60,
      color: 'main_white',
      bg: 'blue.500',
      fontWeight: 700,
      _focus: {
        boxShadow: 'none',
      },
    },
    reset_style_button: {
      bg: 'none',
      color: 'main_black',
      fontWeight: '400',
      borderRadius: 50,
    },
    square_button: {
      h: 'auto',
      borderRadius: 8,
      fontSize: 14,
      py: '2px',
      px: 2,
      bg: 'blue.500',
      color: 'main_white',
      _hover: {
        cursor: 'pointer',
      },
    },
    transparent_button: {
      h: 'auto',
      w: 'fit-content',
      mx: 2,
      py: 2,
      px: 4,
      fontSize: 14,
      borderRadius: 60,
      color: 'gray.100',
      border: '2px solid',
      borderColor: 'gray.50',
      fontWeight: 600,
    },
    increment_button: {
      borderRadius: 60,
      p: 0,
      minW: 4,
      w: 4,
      h: 4,
      m: 1,
      bg: 'gray.100',
      color: 'white',
    },
    position_button: {
      w: 8,
      minW: 0,
      h: 8,
      p: 0,
      borderRadius: 8,
      mr: 2,
      _focus: {
        boxShadow: 'none',
      },
    },
    cancel: {
      h: 'auto',
      py: 4,
      px: 8,
      borderRadius: 60,
      border: '1px solid',
      borderColor: 'gray.500',
      color: 'gray.500',
      fontWeight: 700,
      _focus: {
        boxShadow: 'none',
      },
    },
    save: {
      h: 'auto',
      borderRadius: 60,
      color: 'main_white',
      bg: 'blue.500',
      py: 4,
      px: 8,
      fontWeight: 700,
      _focus: {
        boxShadow: 'none',
      },
    },
    select: {
      w: 'full',
      bg: 'transparent',
      color: 'gray.200',
      fontWeight: 500,
      h: 14,
      justifyContent: 'space-between',
    },
  },
  defaultProps: {
    variant: 'primary_button',
  },
}
