env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - airbnb-typescript
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  semi: [error, never]
  max-len: [error, { code: 100 }]
  implicit-arrow-linebreak: 0
  "@typescript-eslint/semi": [error, never]
  "import/no-default-export": [error]
  "react/react-in-jsx-scope": 0
  "import/prefer-default-export": 0
  "react/function-component-definition": 0
  "no-param-reassign": ['error', { props: true, ignorePropertyModificationsFor: ['state'] }]
